#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

if command -v tmux >/dev/null 2>&1; then
    if [ -z "$TMUX" ]; then
	tmux attach -t main || tmux new -s main
    fi
fi

fastfetch
. ~/.git-prompt.sh
PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 " (%s)")'; PS1='[\[\e[38;5;118m\]\u\[\e[0m\]@\w\[\e[38;5;167m\]${PS1_CMD1}\[\e[0m\]]\$ '
. "$HOME/.cargo/env"
