#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"

if command -v tmux >/dev/null 2>&1; then
    if [ -z "$TMUX" ]; then
	tmux attach -t main || tmux new -s main
    fi
fi

if [ -f /usr/share/git/completion/git-prompt.sh ]; then
    . /usr/share/git/completion/git-prompt.sh
fi

# Enable showing dirty state (uncommitted changes)
export GIT_PS1_SHOWDIRTYSTATE=1

# Enable showing untracked files
export GIT_PS1_SHOWUNTRACKEDFILES=1

# Enable showing stash state
export GIT_PS1_SHOWSTASHSTATE=1

# Customize your PS1 (Prompt String 1)
# This example shows username@hostname:working_directory (git_status)$
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\$ '
